#!/usr/bin/env python3
"""Compose AGENTS.md: inline the memory index and the pinned brand between markers.

Why: @imports only work in Claude Code. Inlined literal text loads in EVERY harness
(Codex, Gemini, Grok, Kimi). Run after any memory/ write, pin change, or pinned-brand edit.
Skills that change those files call this automatically. Safe to run any time.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
AGENTS = ROOT / "AGENTS.md"

def section(marker, content):
    return f"<!-- BEGIN:{marker} (generated by scripts/compose.py, do not hand-edit) -->\n{content.strip()}\n<!-- END:{marker} -->"

def replace(text, marker, content):
    block = section(marker, content)
    pat = re.compile(rf"<!-- BEGIN:{marker}.*?END:{marker} -->", re.S)
    if pat.search(text):
        return pat.sub(lambda m: block, text)
    return text.rstrip() + "\n\n" + block + "\n"

t = AGENTS.read_text(encoding="utf-8")

# 1. memory index, always inlined
mem = (ROOT / "memory" / "MEMORY.md").read_text(encoding="utf-8")
t = replace(t, "MEMORY-INDEX", "## Standing memory (inlined)\n\n" + mem)

# 2. pinned brand, if any
pin_file = ROOT / "companies" / ".pinned"
if pin_file.exists() and pin_file.read_text(encoding="utf-8").strip():
    slug = pin_file.read_text(encoding="utf-8").strip()
    parts = [f"## Primary brand: {slug} (inlined, always loaded)"]
    for name in ("facts.md", "flavor.md"):
        f = ROOT / "companies" / slug / name
        if f.exists():
            parts.append(f"### {slug}/{name}\n\n" + f.read_text(encoding="utf-8").strip())
    t = replace(t, "PINNED-BRAND", "\n\n".join(parts))
else:
    t = replace(t, "PINNED-BRAND", "## Primary brand\n\nNone pinned yet. The company path of /onboard offers to pin one.")

AGENTS.write_text(t, encoding="utf-8")
print("composed: memory index" + (", pinned brand" if pin_file.exists() and pin_file.read_text(encoding='utf-8').strip() else ", no pin"))
